// ─────────────────────────────────────────────────────────────
// Build-time sitemap generator → dist/sitemap.xml
//
// Driven by the same route registry as the prerenderer (src/seo/meta.js),
// so a new route cannot end up prerendered-but-unlisted, or listed-but-404.
// Add the route to meta.js and it appears here automatically.
//
// Blog <lastmod> comes from each post's `date` in src/data/blog.js.
// Everything else uses the build date: these are marketing pages that get
// edited alongside deploys, so "when we last shipped" is the honest answer.
// ─────────────────────────────────────────────────────────────

import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { allRoutes, metaForPath } from '../src/seo/meta.js';
import { absoluteUrl } from '../src/config.js';

const root = dirname(fileURLToPath(new URL('.', import.meta.url)));
const outputPath = join(root, 'dist', 'sitemap.xml');

const BUILD_DATE = new Date().toISOString().slice(0, 10);

/** Crawl priority and expected update cadence, by route. */
const RULES = {
  '/':                 { priority: '1.0', changefreq: 'monthly' },
  '/data/services':    { priority: '0.9', changefreq: 'monthly' },
  '/career/services':  { priority: '0.9', changefreq: 'monthly' },
  '/data/packages':    { priority: '0.8', changefreq: 'monthly' },
  '/career/packages':  { priority: '0.8', changefreq: 'monthly' },
  '/data/contact':     { priority: '0.7', changefreq: 'yearly'  },
  '/career/contact':   { priority: '0.7', changefreq: 'yearly'  },
  '/data/about':       { priority: '0.6', changefreq: 'yearly'  },
  '/career/about':     { priority: '0.6', changefreq: 'yearly'  },
  '/blog':             { priority: '0.6', changefreq: 'weekly'  },
};

const DEFAULT_RULE = { priority: '0.5', changefreq: 'yearly' };

function urlEntry(pathname) {
  const { priority, changefreq } = RULES[pathname] ?? DEFAULT_RULE;
  const lastmod = metaForPath(pathname).date ?? BUILD_DATE;

  return [
    '  <url>',
    `    <loc>${absoluteUrl(pathname)}</loc>`,
    `    <lastmod>${lastmod}</lastmod>`,
    `    <changefreq>${changefreq}</changefreq>`,
    `    <priority>${priority}</priority>`,
    '  </url>',
  ].join('\n');
}

async function main() {
  // A noindex route is prerendered but deliberately kept out of the sitemap —
  // listing it would ask crawlers to fetch a page that then tells them not to
  // index it. Checkout is the first such route.
  const routes = Object.keys(allRoutes()).filter((p) => !metaForPath(p).noindex);

  const xml = [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<!-- Generated by scripts/sitemap.js at build time. Do not edit by hand. -->',
    '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
    ...routes.map(urlEntry),
    '</urlset>',
    '',
  ].join('\n');

  await mkdir(dirname(outputPath), { recursive: true });
  await writeFile(outputPath, xml);

  console.log(`\n✓ sitemap.xml — ${routes.length} URLs`);
}

main().catch((err) => {
  console.error('\n✗ sitemap failed:\n', err);
  process.exit(1);
});
